# Exported from Render on 2025-11-30T18:09:54Z
version: "1"
projects:
- name: My project
  environments:
  - name: Production
    services:
    - type: web
      name: My-Helper
      runtime: docker
      repo: https://github.com/Atharva259/My-Helper
      plan: free
      envVars:
      - key: OPENAI_API_KEY
        sync: false
      region: singapore
      dockerContext: .
      dockerfilePath: /agri connect
      registryCredential:
        fromRegistryCreds:
          name: Logon
      autoDeployTrigger: "off"
      rootDir: Agri connect
